modLoader = "javafml"
loaderVersion = "[41,)"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "bossstack"
version = "${version}"
displayName = "Bossbar stack"
authors = "Cloudburst"
description = '''
Stacks all bossbars with the same name together
'''
logoFile = "icon.png"

[[dependencies.bossstack]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bossstack]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc_version},)"
ordering = "NONE"
side = "BOTH"